name: captain
description: Captain&#x27;s order and customer management

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 0.5.3+1
  permission_handler: ^3.2.0
  sqflite: ^1.3.1+2
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  random_color: ^1.0.5
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  find_dropdown: ^0.2.2
  autocomplete_textfield: ^1.7.3
  uuid: ^2.2.2
  flutter_contact: ^0.6.1
  flutter_colorpicker: ^0.3.4
  sms: ^0.2.4
  flutter_sms: ^2.1.1
  flutter_typeahead: ^1.8.8
  keyboard_visibility: ^0.5.2
  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  path_provider: ^1.6.24
  file_picker: ^2.1.0
  pdf: ^1.12.0
  printing: ^3.7.1
  charts_flutter: ^0.9.0
  flutter_spinkit: ^4.1.2


# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter assets
flutter:
  uses-material-design: true
  assets:
    - assets/images/captain_icon.png
    - assets/images/captain_icon_big_faded.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700