class KapciManufacturers {
  static const List<String> VALUES = [
    "acura",
    "aixam-mega",
    "alfa romeo",
    "angel",
    "aro",
    "asia",
    "aston martin",
    "audi",
    "baic",
    "beijing hyundai",
    "bentley",
    "berkley",
    "beta motorcycles",
    "bmw",
    "bova bus",
    "brilliance auto",
    "brilliance zhonghua",
    "brit. standard range",
    "bugatti",
    "buick",
    "byd auto",
    "cadillac",
    "casalini",
    "chana",
    "chang'an",
    "chang'an ford",
    "chang'an ford mazda",
    "chang'an mazda",
    "chang'an suzuki",
    "changhe",
    "chatenet",
    "chery",
    "chevrolet",
    "chrysler america",
    "citroen",
    "class pays",
    "commercial vehicles amer.",
    "dacia",
    "daelim motorcycles",
    "daewoo",
    "daf",
    "daihatsu",
    "datsun",
    "dodge",
    "dongfeng",
    "dongfeng citroen",
    "dongfeng honda",
    "dongfeng nissan",
    "dongfeng peugeot",
    "dongfeng peugeot citroen",
    "dr",
    "evo bus",
    "faw auto",
    "faw mazda",
    "faw toyota",
    "faw volkswagen",
    "ferrari",
    "fiat / lancia",
    "fiat polski",
    "fleet",
    "ford",
    "ford america",
    "ford australia",
    "foton beijing",
    "fso",
    "gac changfeng",
    "galloper",
    "gaz (volga)",
    "geely",
    "general motors usa",
    "gonow",
    "great wall",
    "guangzhou honda",
    "guangzhou honda",
    "guangzhou toyota",
    "ha fei",
    "ha/ma",
    "haima",
    "hainan mazda",
    "hiali",
    "holden motor co.",
    "honda",
    "hummer",
    "hyundai",
    "india motorcycles",
    "infiniti",
    "innocenti",
    "isuzu",
    "iveco",
    "jac",
    "jaguar",
    "jeep",
    "jianghuai auto",
    "jiangling",
    "jili",
    "ken worth",
    "kia",
    "lada",
    "lamborghini",
    "lancia-autobianchi",
    "land rover",
    "land wind",
    "ldv",
    "lexus",
    "leyland daf",
    "lifan motors",
    "ligier",
    "lotus",
    "luxgen",
    "mahindra",
    "man-buessing",
    "maruti",
    "maserati",
    "maybach",
    "mazda",
    "mbk motorcycles",
    "mclaren automotive",
    "mercedes benz",
    "mercedes trucks",
    "mg",
    "microcar",
    "mini",
    "mitsubishi",
    "morgan",
    "mz motorcycles",
    "nanjing fiat",
    "ncs",
    "neoplan",
    "nissan",
    "nissan commercial",
    "opel/vauxhall",
    "pagani",
    "pantone",
    "perodua",
    "peterbilt",
    "peugeot",
    "pia",
    "piaggio",
    "porsche",
    "proton",
    "ral",
    "ral effect e1",
    "reliant",
    "renault",
    "renault trucks",
    "renault-samsung",
    "roewe",
    "rolls royce",
    "rover",
    "saab",
    "sahin",
    "saic maxus",
    "salc",
    "samsung",
    "san yang",
    "saturn corporation",
    "scania",
    "seat",
    "setra / evobus",
    "sgmw",
    "shanghai general motor",
    "shanghai volkswagen",
    "sinotruk",
    "skoda",
    "smart",
    "soueast motor",
    "ssangyong",
    "subaru/fuji",
    "sunra motorcycles",
    "suzuki",
    "t.v.r.",
    "talbot france",
    "tata",
    "tesla motors",
    "tianjin automobile",
    "tomaso de",
    "toyota",
    "toyota australia",
    "toyota portugal",
    "triumph",
    "umm (movauto)",
    "vauxhall",
    "venturi",
    "volkswagen",
    "volvo",
    "volvo trucks",
    "voxan motorcycles",
    "xiali",
    "yueda kia",
    "yugo/zastava",
    "zhenghou nissan",
    "zotye auto",
  ];
}
