class AddisAbabaRegions {
  static final List<String> regions = [
    "Abacoran Sefer",
    "Abadina Area",
    "Abnet Square",
    "Addis Ketema",
    "Addis Sefer",
    "Adiss",
    "Agusta",
    "Akaki-Kaliti",
    "Amanuel Area",
    "Ambassador",
    "American Gibi",
    "Arat Kilo",
    "Aroge Kera",
    "Aserasement",
    "Asko Area",
    "Asko Bercheko Faberika Area",
    "Atekelet Tera",
    "Atena Tera",
    "Autobus Tera",
    "Aware",
    "Ayat",
    "Ayertena",
    "Nifro Sefer",
    "Bantyiketu",
    "Beg Tera",
    "Beg Tera_10",
    "Beherawi",
    "Bekelo Bet",
    "Berberee Berenda",
    "Besrat Gebriel",
    "Biss Meberat",
    "Bole",
    "Bole Ayat",
    "Bole Mikael",
    "Bomb Tera",
    "Bulgariya Mazoriya",
    "Cabana",
    "Ched Tera",
    "Chew Berenda",
    "Chid Tera",
    "Coca",
    "Darmar",
    "Datsun Sefer",
    "District 3",
    "Doro Manekiya",
    "Doro Tera",
    "Dubai Tera",
    "EECMY Residential Area",
    "Enderase",
    "Enqulal Faberika",
    "Eri Bekentu",
    "Ferash Tera",
    "Gebre Kristos Bete Kristiyan",
    "Gedam Seffer",
    "Geja Seffer",
    "Gerji",
    "Gewasa",
    "Ghiliffalegn Stream",
    "Giorgis",
    "Gojjam Berenda",
    "Golla Mikael",
    "Goma Kuteba",
    "Goma Tera",
    "Gotera",
    "Great Acachi",
    "Gulele Bota",
    "Habete Giorgis",
    "Hadere Sefer",
    "Hana",
    "Harbu Shet'",
    "Irtu Bota",
    "Jemo",
    "Jemo_9",
    "Jos Hanssen",
    "Kara",
    "Kara Alo",
    "Kazanchis",
    "Kebena",
    "Kera",
    "Ketena Hulet",
    "Kirkos",
    "Kolfe Keranio",
    "Kolfe Keranyo",
    "Kolfe Tiwan",
    "Kolobo",
    "Korech Tera",
    "Kotebe",
    "Kurtume Stream",
    "Lafto",
    "Lancha",
    "Lebu",
    "Legahar",
    "Lekwuanda",
    "Lideta",
    "Lideta Gebri'El Bete Kristiyan",
    "Mechare Meda",
    "Medhanialem",
    "Megenagna",
    "Mekanisa",
    "Mekanisa Abo",
    "Menahereya Kazanchis",
    "Menisa",
    "Mennen",
    "Mentaf Tera",
    "Mesalemiya",
    "Meshuwalekiya",
    "Meskel Flower",
    "Mesob Tera",
    "Mexico",
    "Microlink Project",
    "Military Tera",
    "Minalesh Tera",
    "Mobil",
    "Molla Maru",
    "Nefas Silk-Lafto",
    "Olympia",
    "Paster",
    "Piassa (piazza)",
    "Posta Bet",
    "Quasmeda",
    "Ras Mekonnen Deldey",
    "Riche",
    "Rufael",
    "Rwanda",
    "Sarbet",
    "Saris",
    "Saris Abo Area",
    "Satin Tera",
    "Sebara Babur",
    "Sebategna",
    "Sehan Tera",
    "Semien Mezegaja",
    "Serategna Sefer",
    "Shanta Tera",
    "Sheh Ojele (Shegole meda)",
    "Shekela Tera",
    "Shema Tera",
    "Shera Tera",
    "Shero Meda",
    "Shola",
    "Somale Tera",
    "Soste Kuter Mazoria (Total)",
    "Sunshine Real state",
    "Taliyan Sefer",
    "Tekelehaymanot",
    "Tor Hiylloch",
    "Urael",
    "Vatican",
    "Webe Berha",
    "Wello Sefer",
    "Winget",
    "Worik Tera",
    "Yedejazmach Alula Irsha",
    "Yeka",
    "Yeka Bole Bota",
    "Yohannes",
    "Zenebework",
    "Abado Project 13",
    "Arabsa",
    "AU Commissioner residence",
    "Ayat condominiums",
    "Ayat Real Estate Development",
    "Ayat zone 1",
    "Ayat zone 2",
    "Ayat zone 3",
    "Ayat zone 5",
    "Ayat zone 8",
    "Tedros Kasahun",
    "Chefie condominiums",
    "CMC",
    "Condominium",
    "Flintstonehomes Condominium",
    "Habitate",
    "Jemo-1",
    "Jemo-2",
    "Jemo-3",
    "Lafto Condominiums",
    "Lideta Area Condo",
    "Lideta Condominium",
    "Little Texas",
    "Mickey leland condo site",
    "Natan Feleke Kibret Residence",
    "Private",
    "Repi",
    "Repi upper",
    "Sengatera residential area",
    "Southern Addis Ababa Meserete Kristos Church",
    "Sunshine residential",
    "Varnero Real Estate",
    "Villas",
  ];
}